# Generated by Django 2.1.7 on 2019-03-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='persisted',
            field=models.BooleanField(default=False),
        ),
    ]
