# Generated by Django 2.1.7 on 2019-03-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oapi', '0002_wishlist_persisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.CharField(default='No Url', max_length=1024),
        ),
    ]
